version: "3"
services:
  db:
    image: postgres:10.18-alpine
    environment:
      POSTGRES_DB: "dummydbthatisneverused"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5433:5432"

  proxy:
    build: image
    environment:
      TARGET_USER: postgres
      TARGET_PASSWORD: secret
      TARGET_HOST: db:5432
      TARGET_DUMMY_DB: dummydbthatisneverused
    ports:
      - "5432:5432"
